[workspace]

members = [
  "source/logger",
  "source/saksaha",
  "source/crypto",
  "source/proofs",
  "source/peer",
  # "source/process",
  "source/p2p/discovery",
  "source/p2p/identity",
  "source/p2p/active_calls",
  "source/p2p/transport",
  "source/task",

  # internals
  "internals/ci"
]
