[workspace]

members = [
  "logger",
  "saksaha",
  "crypto",
  "proofs",
  "peer",
  "process",
  "p2p/discovery",
  "p2p/identity",
  "p2p/active_calls",
  "p2p/transport",
  "task",

  # internals
  "internals/ci"
]
