[workspace]

members = [
  "source/logger",
  "source/saksaha",
  "source/crypto",
  "source/proofs",
  "source/peer",
  "source/p2p_discovery",
  "source/p2p_identity",
  "source/p2p_active_calls",
  "source/p2p_transport",
  "source/task",

  # internals
  "internals/ci",

  # example
  "example/ci"
]
